### ISSUE TITLE
Adding the dynamic input instead of the static 

### ISSUE THREAD

**Issue by harshpareshbhaigosalya** [Coderu2058/BasicAlgorithms#5]
I will add the dynamic input from the user option instead of the static input.
I have already completed the changes, assign this work to me so that i can pr you.

Thank you @Coderu2058.

**Comment by Dashgreninja** [comment]
You can raise the {R @harshpareshbhaigosalya

**Comment by Coderu2058** [comment]
go ahead @harshpareshbhaigosalya
